source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.3'

# Rails Dependencies
# =====================================================
# Rails, MySQL, Puma
gem "rails", "~> 7.1.3"
gem 'bundler'
gem 'rake', '~> 13.1.0'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'puma', '~> 6.4.0'

# JavaScript/Asset Dependencies
gem 'jquery-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jbuilder', '~> 2.5'

# seeing warnings about these gems not being part of the 
# standard library, they will no longer be included soon
# so adding them here

# Ruby Standard Library Gems
gem 'logger', '~> 1.5.3'
gem 'mutex_m'
gem 'base64'
gem 'bigdecimal'
gem 'drb'
gem 'stringio'
gem 'csv'
gem 'ostruct'
gem 'syslog'

# Add this gem
gem 'logging', '~> 2.3'
gem 'cgi', '~> 0.4.2'

# Frontend Dependencies
# =====================================================
gem "sassc-rails", "~> 2.1"
gem "sprockets-rails"
# gem 'bourbon', '~> 6.0'
# gem 'neat', '~> 2.1'
gem 'bootstrap', '~> 5.3.0'
gem 'turbolinks', '~> 5.2.0'

# loads rails apps faster 
gem 'bootsnap', '>= 1.4.2', require: false

# Application Specific ok 
# =====================================================================================
# cas client
gem 'rack-cas'

# session store
gem 'activerecord-session_store'

# configurations 
gem "figaro"

# security / validation
gem 'validate_url'
gem 'sanitize'
gem 'recaptcha', '~> 5.15'

# frontend
gem 'normalize-scss'
gem "non-stupid-digest-assets" # generates assets without fingerprint for 404 and 500 errors. 
gem 'carrierwave', '~> 2.2'

# searching / indexing for speeds / pagination for elegance
gem 'kaminari'
gem 'elasticsearch-model', '>= 8.0'
gem 'elasticsearch-rails', '>= 8.0'

# jobs
gem 'whenever', require: false

# Test Suite
# =====================================================================================
group :test do
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'simplecov', '~> 0.10', '< 0.18'
  gem 'simplecov-console'
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'selenium-webdriver', '~> 4.4'  
  gem 'elasticsearch-extensions'
  gem 'executables'
  gem 'rspec_junit_formatter'    
  gem 'rails-controller-testing'
  gem 'rack_session_access'
end

# Development / Test Items (Primarily debugging)
# =====================================================================================
group :development, :test do
  gem 'faker'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw] # from rails new
  gem 'pry'
  gem 'pry-rails'
  gem 'factory_bot_rails'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # performance helper
  gem 'bullet' # helps to eliminate N+1 Queries 
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
